'use strict';
/**
 * Copies the front-end libraries and the Poppins font out of node_modules into
 * renderer/vendor, so the app works fully offline (no CDN, no Google Fonts).
 * Runs automatically after `npm install`, before `npm start`, and before `npm run dist`.
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const nm = (...p) => path.join(root, 'node_modules', ...p);
const vendor = path.join(root, 'renderer', 'vendor');

const FILES = [
  [nm('jszip', 'dist', 'jszip.min.js'), 'jszip.min.js'],
  [nm('file-saver', 'dist', 'FileSaver.min.js'), 'FileSaver.min.js'],
  [nm('sortablejs', 'Sortable.min.js'), 'Sortable.min.js'],
  [nm('@fontsource', 'poppins', 'files', 'poppins-latin-400-normal.woff2'), 'fonts/poppins-400.woff2'],
  [nm('@fontsource', 'poppins', 'files', 'poppins-latin-600-normal.woff2'), 'fonts/poppins-600.woff2'],
];

const FONTS_CSS = `/* Generated by scripts/copy-vendor.js - Poppins, served locally. */
@font-face {
  font-family: "Poppins";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("/vendor/fonts/poppins-400.woff2") format("woff2");
}
@font-face {
  font-family: "Poppins";
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url("/vendor/fonts/poppins-600.woff2") format("woff2");
}
`;

let failed = false;
fs.mkdirSync(path.join(vendor, 'fonts'), { recursive: true });

for (const [src, name] of FILES) {
  if (!fs.existsSync(src)) {
    console.error(`[vendor] MISSING: ${path.relative(root, src)}  (run "npm install")`);
    failed = true;
    continue;
  }
  fs.copyFileSync(src, path.join(vendor, name));
}

fs.writeFileSync(path.join(vendor, 'fonts.css'), FONTS_CSS);

if (failed) process.exit(1);
console.log('[vendor] renderer/vendor is ready.');
